access_token: "EAAdxNOWTa5IBO3r42RZAh6lxlFBkiIl4JAogiIn6OxyboZCKrr21FStzjiF41tLQM7BZBiKWhv4W8CbOZBRSUpu0thKXNMbBQgtjbUU6vYVPqs6lYM7X4ZCyHsYCRxPx1ZAXTDEBEZAZBeYO4wazk3ujZA60dDByaeT5Ok7PKX8TwZCM2AZB0DgsSk0METVSl6VLwMMpd05i5IZBESVsz4qTNcwJ8E3904k2gGHKSpAHQ1qpB0WwfoUxOvZCvDZCB8T7UQZBmP6zLAoNt4j0QZDZD"
api_version: "v18.0"
ad_type: "POLITICAL_AND_ISSUE_ADS"
ad_reached_countries: "['NL']"
ad_active_status: "ALL"
search_terms: ""
search_type: "KEYWORD_UNORDERED"
fields:
  - id
  - ad_creation_time
  - ad_creative_bodies
  - ad_delivery_start_time
  - ad_delivery_stop_time
  - impressions
  - spend
  - demographic_distribution
  - delivery_by_region
  - ad_snapshot_url
  - bylines
  - page_id
  - page_name
page_total: 100
max_pages: 330
